{
    created_at: 'Thu May 05 15:25:32 +0000 2016',
    id: 728244244041896000,
    id_str: '728244244041895937',
    text: 'RT @guardian: Junior doctors\' row: Jeremy Hunt and BMA to restart contract talks https://t.co/19AWii0Gho',
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    truncated: false,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
        id: 4767394459,
        id_str: '4767394459',
        name: 'Molly',
        screen_name: 'mollyjoy1998',
        location: null,
        url: 'http://studiesandthat.tumblr.com',
        description: 'constant existential crisis',
        protected: false,
        verified: false,
        followers_count: 66,
        friends_count: 127,
        listed_count: 0,
        favourites_count: 220,
        statuses_count: 177,
        created_at: 'Sat Jan 16 07:51:42 +0000 2016',
        utc_offset: 3600,
        time_zone: 'London',
        geo_enabled: false,
        lang: 'en-gb',
        contributors_enabled: false,
        is_translator: false,
        profile_background_color: 'F5F8FA',
        profile_background_image_url: '',
        profile_background_image_url_https: '',
        profile_background_tile: false,
        profile_link_color: '2B7BB9',
        profile_sidebar_border_color: 'C0DEED',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: true,
        profile_image_url: 'http://pbs.twimg.com/profile_images/724229960177717249/o5bYeHHa_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/724229960177717249/o5bYeHHa_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/4767394459/1461504853',
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
        created_at: 'Thu May 05 13:42:40 +0000 2016',
        id: 728218358454292500,
        id_str: '728218358454292480',
        text: 'Junior doctors\' row: Jeremy Hunt and BMA to restart contract talks https://t.co/19AWii0Gho',
        source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
        truncated: false,
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
            id: 87818409,
            id_str: '87818409',
            name: 'The Guardian',
            screen_name: 'guardian',
            location: 'London',
            url: 'http://theguardian.com',
            description: 'Top stories, special features, live blogs and more',
            protected: false,
            verified: true,
            followers_count: 5535731,
            friends_count: 1112,
            listed_count: 46820,
            favourites_count: 145,
            statuses_count: 239064,
            created_at: 'Thu Nov 05 23:49:19 +0000 2009',
            utc_offset: 3600,
            time_zone: 'London',
            geo_enabled: false,
            lang: 'en',
            contributors_enabled: false,
            is_translator: false,
            profile_background_color: 'FFFFFF',
            profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/704160749/ff996aa3bc2009a2f9b97cdd43e8b5b7.png',
            profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/704160749/ff996aa3bc2009a2f9b97cdd43e8b5b7.png',
            profile_background_tile: false,
            profile_link_color: '005789',
            profile_sidebar_border_color: 'FFFFFF',
            profile_sidebar_fill_color: 'CAE3F3',
            profile_text_color: '333333',
            profile_use_background_image: false,
            profile_image_url: 'http://pbs.twimg.com/profile_images/715857640853741568/nfNt_pGn_normal.jpg',
            profile_image_url_https: 'https://pbs.twimg.com/profile_images/715857640853741568/nfNt_pGn_normal.jpg',
            profile_banner_url: 'https://pbs.twimg.com/profile_banners/87818409/1427295976',
            default_profile: false,
            default_profile_image: false,
            following: null,
            follow_request_sent: null,
            notifications: null
        },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 22,
        favorite_count: 13,
        entities: { hashtags: [], urls: [Object], user_mentions: [], symbols: [] },
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        filter_level: 'low',
        lang: 'en'
    },
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    entities: {
        hashtags: [],
        urls: [
            [Object]
        ],
        user_mentions: [
            [Object]
        ],
        symbols: []
    },
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    filter_level: 'low',
    lang: 'en',
    timestamp_ms: '1462461932560'
}
